name: cryptoProj_env_win
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - setuptools
  - wheel
  - tzdata
  - ca-certificates
  - openssl
  - pip:
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.11.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - distro==1.9.0
      - dnspython==2.8.0
      - email-validator==2.3.0
      - exceptiongroup==1.3.0
      - fastapi==0.121.2
      - fastapi-cli==0.0.16
      - fastapi-cloud-cli==0.3.1
      - h11==0.16.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - idna==3.11
      - jinja2==3.1.6
      - jiter==0.12.0
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - openai==2.8.1
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - python-dotenv==1.2.1
      - python-multipart==0.0.20
      - pyyaml==6.0.3
      - requests==2.32.5
      - rich==14.2.0
      - rich-toolkit==0.15.1
      - rignore==0.7.6
      - sentry-sdk==2.44.0
      - shellingham==1.5.4
      - sniffio==1.3.1
      - starlette==0.49.3
      - tomli==2.3.0
      - tqdm==4.67.1
      - typer==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - watchfiles==1.1.1
      - websockets==15.0.1
